export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SELECTED_PRODUCT_COLOR: "SELECTED_PRODUCT_COLOR",
    SELECTED_INPUT_FILE: "SELECTED_INPUT_FILE",
    SELECTED_DESIGN: "SELECTED_DESIGN",
    DESIGNID: "DESIGNID",
    TEXTFOCUS: "TEXTFOCUS",
    ALLDESIGNS: "ALLDESIGNS",
    DRAGGED: "DRAGGED",
    REVERSETEXT: "REVERSETEXT",
    FLIPTEXT: "FLIPTEXT"
}